spring:
  profiles:
    include:
      - oauth
      - jwt
      - jpa
      - llm

  datasource:
    url: jdbc:mysql://truthai-db.cji480wkeo6g.ap-northeast-2.rds.amazonaws.com:3306/truthAI_rds_db?useSSL=false
    username: admin
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

embedding:
  vec-path: classpath:models/ko-emb.vec  # 또는 file:/절대/경로/ko-emb.vec
  dim: 200

