openai:
  model: gpt-3.5-turbo
  api:
    key: ${GPT_API_KEY}
    url: https://api.openai.com/v1/chat/completions

claude:
  model: claude-3-5-sonnet-20241022
  api:
    key: ${CALUDE_API_KEY}
    url: https://api.anthropic.com

gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: https://generativelanguage.googleapis.com/v1beta

perplexity:
  api:
    key: ${PERPLEXITY_API_KEY}
    url: https://api.perplexity.ai/chat/completions
